### ISSUE TITLE
setupInfiniteScrollReload can now use a new event

### ISSUE THREAD

**Issue by mnn** [NoudH/Ruqqus-viewed-posts-tracker#1]
Hello, regarding this:

```js
//FIXME: preferably this should trigger when the next page is loaded, but I don't think I can hook into RuqES onNextPageSuccessResponse() function.
const setupInfiniteScrollReload = () => {
	const doc = $(document);
	doc.on('scroll', () => {
```

RuqES now emits an event `ruqesinfinitescrollload` when infinite scroll loads a page: https://gitlab.com/enefi/ruqes/-/blob/e306c4eb878a6a9b91494d7fb33dc83e21c1127b/src/common/events.ts

**Comment by NoudH** [comment]
Thanks for the info and sorry for the late reply (almost 1.5 years 😅). Sadly, as you are probably aware of, Ruqqus has shut down. So the project will no longer be maintained.
